### ISSUE TITLE
Plugin crashing after upgrade to 7.x

### ISSUE THREAD

**Issue by cskowronnek** [logstash-plugins/logstash-input-azure_event_hubs#42]
After upgrading Logstash from 6.8 to 7.2 the pipeline seems to crash.
Tried JDK 8 and 11 without success.

[2019-07-09T15:25:10,233][ERROR][logstash.inputs.azureeventhubs] Event Hub failed during initialization. {:event_hub_name=>"iot-demo-hub-to-logstash", :exception=>java.util.concurrent.ExecutionException: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `getEventHubPath' for #<Java::ComMicrosoftAzureEventprocessorhost::HostContext:0x3c583081>, :backtrace=>["java.util.concurrent.CompletableFuture.reportGet(java/util/concurrent/CompletableFuture.java:395)", "java.util.concurrent.CompletableFuture.get(java/util/concurrent/CompletableFuture.java:1999)", "jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)", "jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:62)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:440)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:304)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_input_minus_azure_event_hubs_minus_1_dot_1_dot_0.lib.logstash.inputs.azure_event_hubs.run(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-azure_event_hubs-1.1.0/lib/logstash/inputs/azure_event_hubs.rb:430)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:295)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:270)", "java.lang.Thread.run(java/lang/Thread.java:834)"]}

**Comment by cskowronnek** [comment]
Here is more log output:
``
[2019-07-12T11:18:18,207][ERROR][logstash.agent           ] il.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)", "java.util.stream.ReduceOps$ReduceOp.eva
luateSequential(java/util/stream/ReduceOps.java:913)", "java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)", "java.util.stream.ReferencePipeline.collect(
java/util/stream/ReferencePipeline.java:578)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.compileDependencies(org/logstash/config/ir/CompiledPipeline.java:400)", "org.logsta
sh.config.ir.CompiledPipeline$CompiledExecution.flatten(org/logstash/config/ir/CompiledPipeline.java:361)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.filterDataset(org/logs
tash/config/ir/CompiledPipeline.java:287)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.lambda$compileDependencies$4(org/logstash/config/ir/CompiledPipeline.java:379)", "java
.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)", "java.util.stream.ReferencePipeline$2$1.accept(java/util/stream/ReferencePipeline.java:177)", "java.
util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)", "java.util.Iterator.forEachRemaining(java/util/Iterator.java:133)", "java.util.Spliterators$IteratorS
pliterator.forEachRemaining(java/util/Spliterators.java:1801)", "java.util.stream.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:484)", "java.util.stream.AbstractPipeline.
wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)", "java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java/util/stream/ReduceOps.java:913)", "java.util.stream.AbstractPipeli
ne.evaluate(java/util/stream/AbstractPipeline.java:234)", "java.util.stream.ReferencePipeline.collect(java/util/stream/ReferencePipeline.java:578)", "org.logstash.config.ir.CompiledPipeline
$CompiledExecution.compileDependencies(org/logstash/config/ir/CompiledPipeline.java:400)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.flatten(org/logstash/config/ir/Compiled
Pipeline.java:361)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.filterDataset(org/logstash/config/ir/CompiledPipeline.java:287)", "org.logstash.config.ir.CompiledPipeline$Co
mpiledExecution.lambda$compileDependencies$4(org/logstash/config/ir/CompiledPipeline.java:379)", "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)"
, "java.util.stream.ReferencePipeline$2$1.accept(java/util/stream/ReferencePipeline.java:177)", "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)",
 "java.util.Iterator.forEachRemaining(java/util/Iterator.java:133)", "java.util.Spliterators$IteratorSpliterator.forEachRemaining(java/util/Spliterators.java:1801)", "java.util.stream.Abstr
actPipeline.copyInto(java/util/stream/AbstractPipeline.java:484)", "java.util.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)", "java.util.stream.ReduceO
ps$ReduceOp.evaluateSequential(java/util/stream/ReduceOps.java:913)", "java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)", "java.util.stream.ReferencePi
peline.collect(java/util/stream/ReferencePipeline.java:578)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.compileDependencies(org/logstash/config/ir/CompiledPipeline.java:400
)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.flatten(org/logstash/config/ir/CompiledPipeline.java:361)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.split(o
rg/logstash/config/ir/CompiledPipeline.java:332)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.lambda$compileDependencies$4(org/logstash/config/ir/CompiledPipeline.java:386)"
, "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)", "java.util.stream.ReferencePipeline$2$1.accept(java/util/stream/ReferencePipeline.java:177)",
 "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)", "java.util.Iterator.forEachRemaining(java/util/Iterator.java:133)", "java.util.Spliterators$It
eratorSpliterator.forEachRemaining(java/util/Spliterators.java:1801)", "java.util.stream.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:484)", "java.util.stream.AbstractPi
peline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)", "java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java/util/stream/ReduceOps.java:913)", "java.util.stream.Abstrac
tPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)", "java.util.stream.ReferencePipeline.collect(java/util/stream/ReferencePipeline.java:578)", "org.logstash.config.ir.CompiledP
ipeline$CompiledExecution.compileDependencies(org/logstash/config/ir/CompiledPipeline.java:400)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.flatten(org/logstash/config/ir/C
ompiledPipeline.java:361)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.filterDataset(org/logstash/config/ir/CompiledPipeline.java:287)", "org.logstash.config.ir.CompiledPipe
line$CompiledExecution.lambda$compileDependencies$4(org/logstash/config/ir/CompiledPipeline.java:379)", "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.jav
a:195)", "java.util.stream.ReferencePipeline$2$1.accept(java/util/stream/ReferencePipeline.java:177)", "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java
:195)", "java.util.Iterator.forEachRemaining(java/util/Iterator.java:133)", "java.util.Spliterators$IteratorSpliterator.forEachRemaining(java/util/Spliterators.java:1801)", "java.util.strea
m.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:484)", "java.util.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)", "java.util.stream.
ReduceOps$ReduceOp.evaluateSequential(java/util/stream/ReduceOps.java:913)", "java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)", "java.util.stream.Refe
rencePipeline.collect(java/util/stream/ReferencePipeline.java:578)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.compileDependencies(org/logstash/config/ir/CompiledPipeline.j
ava:400)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.flatten(org/logstash/config/ir/CompiledPipeline.java:361)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.
split(org/logstash/config/ir/CompiledPipeline.java:332)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.lambda$compileDependencies$4(org/logstash/config/ir/CompiledPipeline.jav
a:386)", "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)", "java.util.stream.ReferencePipeline$2$1.accept(java/util/stream/ReferencePipeline.java
:177)", "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)", "java.util.Iterator.forEachRemaining(java/util/Iterator.java:133)", "java.util.Splitera
tors$IteratorSpliterator.forEachRemaining(java/util/Spliterators.java:1801)", "java.util.stream.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:484)", "java.util.stream.Abs
tractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)", "java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java/util/stream/ReduceOps.java:913)", "java.util.stream.
AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)", "java.util.stream.ReferencePipeline.collect(java/util/stream/ReferencePipeline.java:578)", "org.logstash.config.ir.Co
mpiledPipeline$CompiledExecution.compileDependencies(org/logstash/config/ir/CompiledPipeline.java:400)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.flatten(org/logstash/conf
ig/ir/CompiledPipeline.java:361)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.lambda$compile$1(org/logstash/config/ir/CompiledPipeline.java:270)", "java.util.stream.Referenc
ePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)", "java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java/util/ArrayList.java:1654)", "java.util.stream.AbstractPip
eline.copyInto(java/util/stream/AbstractPipeline.java:484)", "java.util.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)", "java.util.stream.ReduceOps$Red
uceOp.evaluateSequential(java/util/stream/ReduceOps.java:913)", "java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)", "java.util.stream.ReferencePipeline
.collect(java/util/stream/ReferencePipeline.java:578)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.compile(org/logstash/config/ir/CompiledPipeline.java:271)", "org.logstash.config.ir.CompiledPipeline$CompiledExecution.<init>(org/logstash/config/ir/CompiledPipeline.java:251)", "org.logstash.config.ir.CompiledPipeline.buildExecution(org/logstash/config/ir/CompiledPipeline.java:103)", "org.logstash.execution.WorkerLoop.<init>(org/logstash/execution/WorkerLoop.java:46)", "jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)", "jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(jdk/internal/reflect/NativeConstructorAccessorImpl.java:62)", "jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(jdk/internal/reflect/DelegatingConstructorAccessorImpl.java:45)", "java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:490)", "org.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/JavaConstructor.java:247)", "org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:915)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)", "usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:239)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:295)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:270)", "java.lang.Thread.run(java/lang/Thread.java:834)"]}
``

**Comment by cskowronnek** [comment]
Sorry, this error was caused by a faulty pipeline. Nothing related to the plugin

**Comment by pgorczynski** [comment]
@cskowronnek do you remember what was the issue with pipeline? I have just the same issue 😞

**Comment by pgorczynski** [comment]
Ok, I have found other issue (https://github.com/elastic/logstash/issues/11050#issuecomment-521262731) that have fix that worked for me:

`bin/logstash-plugin update logstash-input-azure_event_hubs`
